### ISSUE TITLE
[Feature Request] More Helpful Exit on Panic

### ISSUE THREAD

**Issue by luxlogica** [mikefarah/yq#174]
Malformed YAML will crash the parser, but it exits by outputting a quite unhelpful message - example:

```
panic: attempted to parse unknown event: none [recovered]
	panic: attempted to parse unknown event: none

goroutine 1 [running]:
github.com/mikefarah/yq/vendor/gopkg.in/mikefarah/yaml%2ev2.handleErr(0x10661d30)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/mikefarah/yaml.v2/yaml.go:249 +0x75
panic(0x18cb20, 0x10692530)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/panic.go:502 +0x1cd
github.com/mikefarah/yq/vendor/gopkg.in/mikefarah/yaml%2ev2.(*parser).parse(0x106b6480, 0x1caa28)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/mikefarah/yaml.v2/decode.go:158 +0x156
github.com/mikefarah/yq/vendor/gopkg.in/mikefarah/yaml%2ev2.(*Decoder).Decode(0x10692490, 0x177c00, 0x10692480, 0x0, 0x0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/mikefarah/yaml.v2/yaml.go:122 +0xc4
main.readProperty.func1(0x10692490, 0x10692488, 0x10692490)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/yq.go:231 +0x79
main.readStream(0xbffffc71, 0x56, 0x10696be0, 0x0, 0x0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/yq.go:616 +0xa7
main.readProperty(0x106cc280, 0x106a8290, 0x2, 0x2, 0x0, 0x0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/yq.go:229 +0x130
github.com/mikefarah/yq/vendor/gopkg.in/spf13/cobra%2ev0.(*Command).execute(0x106cc280, 0x106a8230, 0x2, 0x2, 0x106cc280, 0x106a8230)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/spf13/cobra.v0/command.go:762 +0x34d
github.com/mikefarah/yq/vendor/gopkg.in/spf13/cobra%2ev0.(*Command).ExecuteC(0x106cc140, 0x106cc500, 0x106cc640, 0x106cc780)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/spf13/cobra.v0/command.go:852 +0x284
github.com/mikefarah/yq/vendor/gopkg.in/spf13/cobra%2ev0.(*Command).Execute(0x106cc140, 0x0, 0x0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/spf13/cobra.v0/command.go:800 +0x1b
main.main()
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/yq.go:33 +0x19
```

Of course, it would be much more helpful if we could actually get an idea of where in the YAML file the error is - ie., a line number. The output of [yaml2json](https://github.com/bronze1man/yaml2json) for the same problematic file is...:

```
yaml: line 43: did not find expected key
```

...which helps a lot!

This feature request may be related/similar to Issue #124.

**Comment by mikefarah** [comment]
Hi, thanks for raising this, do you have a sample input that produces that error?

**Comment by luxlogica** [comment]
Try this:

``` yaml
settings:
  title: 'Title' Goes Here
```

The single-quotes at the beginning of an unquoted string literal value will do it.

**Comment by combor** [comment]
Yeah, this is bit confusing while it panics. Panics supposed to be used only due to unrecoverable internal errors ( like nil pointers etc ) but in this case it would be much more helpful for the user to return `Invalid yaml` or something similar.

Test case:
```
a:
b: c
  d: e
```

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.0.1
