### ISSUE TITLE
Index out of range on `delete someArray.*`

### ISSUE THREAD

**Issue by abidon** [mikefarah/yq#293]
Hello,

I recently experienced a bug in yq (version 2.4.0) when running the following two commands:

- `yq delete /etc/filebeat/filebeat.yml 'processors.*'`
- `yq delete /etc/filebeat/filebeat.yml 'processors[*]'`

On a file like this:

```
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
```

Here is the stack trace:
```
panic: runtime error: index out of range

goroutine 1 [running]:
main.deleteChildValue(0x5df2e0, 0xc00000c980, 0xc00000c5b0, 0x0, 0x0, 0x2, 0x5, 0x0, 0xc00000cf00)
        /build/yq/parts/yq/go/src/github.com/mikefarah/yq/data_navigator.go:333 +0x561
main.deleteArraySplat(0xc00000c8a0, 0x2, 0x2, 0xc00000c5b0, 0x0, 0x0, 0x46a0b2, 0x0, 0x0, 0xc000089210)
        /build/yq/parts/yq/go/src/github.com/mikefarah/yq/data_navigator.go:296 +0x20f
main.deleteChildValue(0x5d0b20, 0xc00000ca60, 0xc00000c5b0, 0x1, 0x1, 0x0, 0xc00004ac30, 0x0, 0x7bab40)
        /build/yq/parts/yq/go/src/github.com/mikefarah/yq/data_navigator.go:340 +0x349
main.deleteEntryInMap(0xc0000b2e00, 0x6, 0x8, 0x5d54c0, 0xc00004aa90, 0x5d0b20, 0xc00000ca60, 0x3, 0xc00000c5a0, 0x2, ...)
        /build/yq/parts/yq/go/src/github.com/mikefarah/yq/data_navigator.go:269 +0x3d6
main.deleteMap(0x5df2e0, 0xc00000ce80, 0xc00000c5a0, 0x2, 0x2, 0x2, 0xc0000894a8, 0x549bf9, 0xc000068a80, 0x5)
        /build/yq/parts/yq/go/src/github.com/mikefarah/yq/data_navigator.go:251 +0x415
main.deleteChildValue(0x5df2e0, 0xc00000ce20, 0xc00000c5a0, 0x2, 0x2, 0x1, 0x620056, 0xc00007dc00, 0xc000010540)
        /build/yq/parts/yq/go/src/github.com/mikefarah/yq/data_navigator.go:337 +0x44b
main.deleteProperty.func1(0x5df2e0, 0xc00000ce20, 0x0, 0x0, 0x0, 0x1, 0x203000)
        /build/yq/parts/yq/go/src/github.com/mikefarah/yq/yq.go:508 +0x102
main.mapYamlDecoder.func1(0xc00004a960, 0xc00004a960, 0x600)
        /build/yq/parts/yq/go/src/github.com/mikefarah/yq/yq.go:387 +0x1d6
main.readStream(0x7ffed875b5de, 0x1a, 0xc00000c5e0, 0x0, 0x0)
        /build/yq/parts/yq/go/src/github.com/mikefarah/yq/yq.go:691 +0x274
main.readAndUpdate(0x656ce0, 0xc00000e020, 0x7ffed875b5de, 0x1a, 0xc000068f30, 0x0, 0x0)
        /build/yq/parts/yq/go/src/github.com/mikefarah/yq/yq.go:491 +0x4dd
main.deleteProperty(0xc00008d180, 0xc00000c4e0, 0x2, 0x2, 0x0, 0x0)
        /build/yq/parts/yq/go/src/github.com/mikefarah/yq/yq.go:513 +0x13b
gopkg.in/spf13/cobra%2ev0.(*Command).execute(0xc00008d180, 0xc00000c420, 0x2, 0x2, 0xc00008d180, 0xc00000c420)
        /build/yq/parts/yq/go/src/gopkg.in/spf13/cobra.v0/command.go:762 +0x473
gopkg.in/spf13/cobra%2ev0.(*Command).ExecuteC(0xc00008c780, 0xc00008d180, 0xc00008d400, 0xc00008d680)
        /build/yq/parts/yq/go/src/gopkg.in/spf13/cobra.v0/command.go:852 +0x2fd
gopkg.in/spf13/cobra%2ev0.(*Command).Execute(0xc00008c780, 0xc000089f88, 0x0)
        /build/yq/parts/yq/go/src/gopkg.in/spf13/cobra.v0/command.go:800 +0x2b
main.main()
        /build/yq/parts/yq/go/src/github.com/mikefarah/yq/yq.go:34 +0x27
```

**Comment by abidon** [comment]
If it happens to someone else, a quick fix is to delete the key and recreate it, i.e.:
```
yq delete your_file processors
yq write your_file processors.[+] some_value
```

**Comment by mikefarah** [comment]
Yeah you should be able to delete all the array elements, bummer

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.0.1 :)
