### ISSUE TITLE
parse fails, depending on document contents

### ISSUE THREAD

**Issue by mccalluc** [mikefarah/yq#294]
(This might be subsumed under #188, or perhaps #174.)

I don't believe the document body after the yaml header should make a difference, but it does. This example works:
```
$ cat ~/Desktop/good.md
---
field: value
---
But this is just: text.
$ yq r ~/Desktop/good.md
field: value
```
But this:
```
---
field: value
---
But this is just: text.

Add another line and it breaks...
```
Produces this:
```
panic: attempted to parse unknown event: none [recovered]
	panic: attempted to parse unknown event: none

goroutine 1 [running]:
github.com/mikefarah/yaml/v2.handleErr(0xc0000c7a60)
	/private/tmp/yq-20191103-94828-1le9481/yq-2.4.1/pkg/mod/github.com/mikefarah/yaml/v2@v2.4.0/yaml.go:249 +0x9a
panic(0x11f7180, 0xc00009ab30)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/panic.go:679 +0x1b2
github.com/mikefarah/yaml/v2.(*parser).parse(0xc000106000, 0xc000088380)
	/private/tmp/yq-20191103-94828-1le9481/yq-2.4.1/pkg/mod/github.com/mikefarah/yaml/v2@v2.4.0/decode.go:158 +0x25f
github.com/mikefarah/yaml/v2.(*Decoder).Decode(0xc00009aa80, 0x11ebde0, 0xc00009aa70, 0x0, 0x0)
	/private/tmp/yq-20191103-94828-1le9481/yq-2.4.1/pkg/mod/github.com/mikefarah/yaml/v2@v2.4.0/yaml.go:122 +0xff
main.readProperty.func1(0xc00009aa80, 0xc00009aa80, 0x600)
	/private/tmp/yq-20191103-94828-1le9481/yq-2.4.1/src/github.com/mikefarah/yq/yq.go:262 +0xa8
main.readStream(0x7ffeefbffa9d, 0x1b, 0xc0000c7d10, 0x0, 0x0)
	/private/tmp/yq-20191103-94828-1le9481/yq-2.4.1/src/github.com/mikefarah/yq/yq.go:696 +0x253
main.readProperty(0xc0000cec80, 0xc00009aa20, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/yq-20191103-94828-1le9481/yq-2.4.1/src/github.com/mikefarah/yq/yq.go:260 +0x179
github.com/spf13/cobra.(*Command).execute(0xc0000cec80, 0xc00009a9c0, 0x1, 0x1, 0xc0000cec80, 0xc00009a9c0)
	/private/tmp/yq-20191103-94828-1le9481/yq-2.4.1/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000cea00, 0x1005d5f, 0xc00008a058, 0x0)
	/private/tmp/yq-20191103-94828-1le9481/yq-2.4.1/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/private/tmp/yq-20191103-94828-1le9481/yq-2.4.1/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/private/tmp/yq-20191103-94828-1le9481/yq-2.4.1/src/github.com/mikefarah/yq/yq.go:34 +0x2b
```

**Comment by mikefarah** [comment]
Hmm on further inspection - there's no real way of knowing that a particular document is not yaml and just plain text. At least not that I can see

**Comment by mikefarah** [comment]
The latest release https://github.com/mikefarah/yq/releases/tag/3.0.1 fixes this.

It won't have a parsing error when reading the first doc, but will still fail if you attempt to parse that doc index specifically, but it will fail gracefully.
