### ISSUE TITLE
Failed to parse json file

### ISSUE THREAD

**Issue by adanilinel1** [mikefarah/yq#297]
yq 2.4.1
```
panic: attempted to parse unknown event: none [recovered]
        panic: attempted to parse unknown event: none

goroutine 1 [running]:
github.com/mikefarah/yaml/v2.handleErr(0xc0000d3a60)
        /private/tmp/yq-20191103-68962-1jih3cn/yq-2.4.1/pkg/mod/github.com/mikefarah/yaml/v2@v2.4.0/yaml.go:249 +0x9a
panic(0x11f71c0, 0xc0000a4c60)
        /usr/local/Cellar/go/1.13.4/libexec/src/runtime/panic.go:679 +0x1b2
github.com/mikefarah/yaml/v2.(*parser).parse(0xc000110000, 0xc000098680)
        /private/tmp/yq-20191103-68962-1jih3cn/yq-2.4.1/pkg/mod/github.com/mikefarah/yaml/v2@v2.4.0/decode.go:158 +0x25f
github.com/mikefarah/yaml/v2.(*Decoder).Decode(0xc0000a4a80, 0x11ebe20, 0xc0000a4a70, 0x0, 0x0)
        /private/tmp/yq-20191103-68962-1jih3cn/yq-2.4.1/pkg/mod/github.com/mikefarah/yaml/v2@v2.4.0/yaml.go:122 +0xff
main.readProperty.func1(0xc0000a4a80, 0xc0000a4a80, 0x600)
        /private/tmp/yq-20191103-68962-1jih3cn/yq-2.4.1/src/github.com/mikefarah/yq/yq.go:262 +0xa8
main.readStream(0x7ffeefbff6fd, 0xc, 0xc0000d3d10, 0x0, 0x0)
        /private/tmp/yq-20191103-68962-1jih3cn/yq-2.4.1/src/github.com/mikefarah/yq/yq.go:696 +0x253
main.readProperty(0xc0000dac80, 0xc0000a4a20, 0x1, 0x1, 0x0, 0x0)
        /private/tmp/yq-20191103-68962-1jih3cn/yq-2.4.1/src/github.com/mikefarah/yq/yq.go:260 +0x179
github.com/spf13/cobra.(*Command).execute(0xc0000dac80, 0xc0000a49c0, 0x1, 0x1, 0xc0000dac80, 0xc0000a49c0)
        /private/tmp/yq-20191103-68962-1jih3cn/yq-2.4.1/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000daa00, 0x1005d9f, 0xc00009a058, 0x0)
        /private/tmp/yq-20191103-68962-1jih3cn/yq-2.4.1/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /private/tmp/yq-20191103-68962-1jih3cn/yq-2.4.1/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /private/tmp/yq-20191103-68962-1jih3cn/yq-2.4.1/src/github.com/mikefarah/yq/yq.go:34 +0x2b
```

**Comment by mikefarah** [comment]
can't help you unless you give a sample json and command...
