### ISSUE TITLE
All yq commands on linux s390x nil pointer exception

### ISSUE THREAD

**Issue by samuel-hawker** [mikefarah/yq#394]
**Describe the bug**
This bug is present on versions 3+ (I tried version 3.0.1 3.1.1 and 3.2.1) of yq with all commands that I tried. The 

**Input Yaml**
Very basic input as copied from the docs
sample.yaml:
```
b:
  c: 2
```

**Command**
The command you ran:
```
yq w sample.yaml b.c cat
```

**Actual behavior**

Ran with yq v3.2.1 as latest version
```
./yq w sample.yaml b.c cat
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15cb12]

goroutine 1 [running]:
gopkg.in/yaml%2ev3.handleErr(0xc000079990)
	/Users/mikefarah/dev/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200121175148-a6ecf24a6d71/yaml.go:276 +0xb2
panic(0x270aa0, 0x473240)
	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/panic.go:679 +0x1d4
gopkg.in/yaml%2ev3.yaml_parser_parse_node(0xc0000d8800, 0xc0000d8ab0, 0x100000000000000, 0x0)
	/Users/mikefarah/dev/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200121175148-a6ecf24a6d71/parserc.go:564 +0x4c2
gopkg.in/yaml%2ev3.yaml_parser_state_machine(0xc0000d8800, 0xc0000d8ab0, 0xc0000b7cc0)
	/Users/mikefarah/dev/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200121175148-a6ecf24a6d71/parserc.go:170 +0x1c6
gopkg.in/yaml%2ev3.yaml_parser_parse(0xc0000d8800, 0xc0000d8ab0, 0x3ffacfc0d98)
	/Users/mikefarah/dev/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200121175148-a6ecf24a6d71/parserc.go:129 +0x8a
gopkg.in/yaml%2ev3.(*parser).peek(0xc0000d8800, 0x0)
	/Users/mikefarah/dev/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200121175148-a6ecf24a6d71/decode.go:102 +0x42
gopkg.in/yaml%2ev3.(*parser).parse(0xc0000d8800, 0x0)
	/Users/mikefarah/dev/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200121175148-a6ecf24a6d71/decode.go:141 +0x38
gopkg.in/yaml%2ev3.(*parser).parseChild(0xc0000d8800, 0xc0000b7cc0, 0x0)
	/Users/mikefarah/dev/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200121175148-a6ecf24a6d71/decode.go:186 +0x2a
gopkg.in/yaml%2ev3.(*parser).document(0xc0000d8800, 0x300000000000030)
	/Users/mikefarah/dev/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200121175148-a6ecf24a6d71/decode.go:195 +0xa8
gopkg.in/yaml%2ev3.(*parser).parse(0xc0000d8800, 0xc0000b9c70)
	/Users/mikefarah/dev/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200121175148-a6ecf24a6d71/decode.go:151 +0x154
gopkg.in/yaml%2ev3.(*Decoder).Decode(0xc000084a20, 0x282380, 0xc0000b7c20, 0x0, 0x0)
	/Users/mikefarah/dev/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200121175148-a6ecf24a6d71/yaml.go:123 +0x120
github.com/mikefarah/yq/v3/cmd.mapYamlDecoder.func1(0xc000084a20, 0xc000084a20, 0x600)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/cmd/utils.go:254 +0x16c
github.com/mikefarah/yq/v3/cmd.readStream(0x3fff997f87e, 0xb, 0xc0000ac500, 0x0, 0x0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/cmd/utils.go:490 +0x23a
github.com/mikefarah/yq/v3/cmd.readAndUpdate(0x302160, 0xc00009a008, 0x3fff997f87e, 0xb, 0xc0000894d0, 0x0, 0x0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/cmd/utils.go:370 +0x288
github.com/mikefarah/yq/v3/cmd.updateDoc(0x3fff997f87e, 0xb, 0xc0000894a0, 0x1, 0x1, 0x302160, 0xc00009a008, 0x1, 0x1)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/cmd/utils.go:328 +0xe4
github.com/mikefarah/yq/v3/cmd.writeProperty(0xc0000bd400, 0xc0000893b0, 0x3, 0x3, 0x0, 0x0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/cmd/write.go:57 +0x106
github.com/spf13/cobra.(*Command).execute(0xc0000bd400, 0xc000089290, 0x3, 0x3, 0xc0000bd400, 0xc000089290)
	/Users/mikefarah/dev/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x404
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000bca00, 0x2, 0xc000089230, 0xc000082058)
	/Users/mikefarah/dev/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2aa
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/mikefarah/dev/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/yq.go:13 +0x60
```

**Expected behavior**
sample.yaml
```
b:
  c: cat
```

**Additional context**
From what I can see it appears that it is unable to decode what it is reading (which would explain why all commands fail)

**Comment by mikefarah** [comment]
Bum - I'm using gox to cross compile the binaries - searching in that repo revealed this comment:

```
// While not fully supported s390x is generally useful
```
https://github.com/mitchellh/gox/blob/e05df8dccde397491cd731693a93d4506b5850d3/platform.go

Perhaps raise a bug there and reference this issue? I don't think I can do much to help as I dont have anything running that architecture - nor would I know how to fix cross compilation issues ;(

**Comment by samuel-hawker** [comment]
Hi Mike, thanks for the prompt response.

Really appreciate your help in this issue, `yq` is a fantastically useful tool, I will raise a bug there as you suggest and let you know if I get any traction on fixing this issue. 

Would it be possible to get a rebuild of s390x in the case that the cross-compilation issues are resolved? 🙏

**Comment by jschintag** [comment]
Hi, i have the same issue on s390x. I can confirm that a natively build yq does not have this issue.

/cc @alicefr

**Comment by samuel-hawker** [comment]
@jschintag I have built it natively (linux s390x) and still have the same issue...

Did you run anything special aside from `make vendor` and `go build -o ya .`?

**Comment by jschintag** [comment]
@samuel-hawker i just run `make local build`. You might have to set `GO111MODULE=on` first or add it as enviroment

**Comment by alicefr** [comment]
@samuel-hawker it's not a problem with cross-compilation. It depends on the go version. I guess we found a bug in golang for s390x. I compiled yq natively using 2 different go version:
go 1.12.3
```sh
./yq-go-1.12.3 w sample.yaml b.c cat
b:
  c: cat
```
go 1.14.1:
```sh
./yq-go-1.14.1 w sample.yaml b.c cat
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x150676]

goroutine 1 [running]:
gopkg.in/yaml%2ev3.handleErr(0xc000113a10)
	/root/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200121175148-a6ecf24a6d71/yaml.go:276 +0xae
panic(0x2598e0, 0x464540)
	/usr/local/go/src/runtime/panic.go:967 +0x132
gopkg.in/yaml%2ev3.yaml_parser_parse_node(0xc00014c000, 0xc00014c2b0, 0x100000000000080, 0x2e)
	/root/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200121175148-a6ecf24a6d71/parserc.go:564 +0x496
gopkg.in/yaml%2ev3.yaml_parser_state_machine(0xc00014c000, 0xc00014c2b0, 0x3ff8b944db8)
	/root/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200121175148-a6ecf24a6d71/parserc.go:170 +0x1a4
gopkg.in/yaml%2ev3.yaml_parser_parse(0xc00014c000, 0xc00014c2b0, 0x3ff8b93a108)
	/root/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200121175148-a6ecf24a6d71/parserc.go:129 +0x82
gopkg.in/yaml%2ev3.(*parser).peek(0xc00014c000, 0x0)
	/root/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200121175148-a6ecf24a6d71/decode.go:102 +0x3c
gopkg.in/yaml%2ev3.(*parser).parse(0xc00014c000, 0x0)
	/root/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200121175148-a6ecf24a6d71/decode.go:141 +0x36
gopkg.in/yaml%2ev3.(*parser).parseChild(0xc00014c000, 0xc00010bc20, 0x0)
	/root/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200121175148-a6ecf24a6d71/decode.go:186 +0x2a
gopkg.in/yaml%2ev3.(*parser).document(0xc00014c000, 0x300000000000030)
	/root/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200121175148-a6ecf24a6d71/decode.go:195 +0xa6
gopkg.in/yaml%2ev3.(*parser).parse(0xc00014c000, 0xc00010dc70)
	/root/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200121175148-a6ecf24a6d71/decode.go:151 +0x13a
gopkg.in/yaml%2ev3.(*Decoder).Decode(0xc000048a40, 0x26a2a0, 0xc00010bb80, 0x0, 0x0)
	/root/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200121175148-a6ecf24a6d71/yaml.go:123 +0xfe
github.com/mikefarah/yq/v3/cmd.mapYamlDecoder.func1(0xc000048a40, 0xc000048a40, 0x600)
	/root/go/src/github.com/mikefarah/yq/cmd/utils.go:254 +0x166
github.com/mikefarah/yq/v3/cmd.readStream(0x3ffcd3ff792, 0xb, 0xc00000e5a0, 0x0, 0x0)
	/root/go/src/github.com/mikefarah/yq/cmd/utils.go:490 +0x20e
github.com/mikefarah/yq/v3/cmd.readAndUpdate(0x2e9600, 0xc000010018, 0x3ffcd3ff792, 0xb, 0xc0000734d0, 0x0, 0x0)
	/root/go/src/github.com/mikefarah/yq/cmd/utils.go:370 +0x286
github.com/mikefarah/yq/v3/cmd.updateDoc(0x3ffcd3ff792, 0xb, 0xc0000734a0, 0x1, 0x1, 0x2e9600, 0xc000010018, 0x1, 0x1)
	/root/go/src/github.com/mikefarah/yq/cmd/utils.go:328 +0xdc
github.com/mikefarah/yq/v3/cmd.writeProperty(0xc000117400, 0xc0000733b0, 0x3, 0x3, 0x0, 0x0)
	/root/go/src/github.com/mikefarah/yq/cmd/write.go:57 +0x100
github.com/spf13/cobra.(*Command).execute(0xc000117400, 0xc000073290, 0x3, 0x3, 0xc000117400, 0xc000073290)
	/root/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x3c4
github.com/spf13/cobra.(*Command).ExecuteC(0xc000116a00, 0x2, 0xc000073230, 0xc000068058)
	/root/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x29e
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/root/go/src/github.com/mikefarah/yq/yq.go:13 +0x60

```
So, a quick workaround is to use an older go version. We'll try to search the go bug.

**Comment by samuel-hawker** [comment]
@alicefr thank you so much, it looks like you're absolutely right, it's a problem with newer versions of go :(
I'll use a back level version thank you so much!

**Comment by alicefr** [comment]
to track the problem. Here the issue https://github.com/golang/go/issues/38195
