### ISSUE TITLE
panic during merge of files with schema differences

### ISSUE THREAD

**Issue by davidkonigsberg** [mikefarah/yq#592]
**Describe the bug**
When two files are merged which contain slightly different structure, depending on the order of the merge yq will panic. Would be nice if it gave an error message instead.

Version of yq: 3.4.1
Operating system: **Mac**
Installed via: **binary release**

**Input Yaml**
data1.yml:
```yaml
global:
  labels:
    label1:
```

data2.yml:
```yaml
global:
  labels:
    - label1
```

**Command**
```
yq m -x data2.yml data1.yml
```

**Actual behavior**

```yaml
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).recurseMap.func1(0xc0000a0108, 0x1, 0x1, 0x0, 0xc000119140, 0x3)
	/home/mikefarah/dev/yq/pkg/yqlib/data_navigator.go:127 +0x94a
github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).visitDirectMatchingEntries(0xc00008fee0, 0xc000100dc0, 0xc0000a7496, 0x6, 0xc0000a46b0, 0x0, 0x1, 0xc0000b6e80, 0x2, 0x2, ...)
	/home/mikefarah/dev/yq/pkg/yqlib/data_navigator.go:178 +0x202
github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).visitMatchingEntries(0xc00008fee0, 0xc000100dc0, 0xc0000a7496, 0x6, 0xc0000a46b0, 0x0, 0x1, 0xc0000b6e80, 0x2, 0x2, ...)
	/home/mikefarah/dev/yq/pkg/yqlib/data_navigator.go:194 +0x1bc
github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).recurseMap(0xc00008fee0, 0xc000100dc0, 0xc0000a7496, 0x6, 0xc0000a46b0, 0x0, 0x1, 0xc0000b6e80, 0x2, 0x2, ...)
	/home/mikefarah/dev/yq/pkg/yqlib/data_navigator.go:121 +0x158
github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).recurse(0xc00008fee0, 0xc000100dc0, 0x1239780, 0xc00008fed0, 0xc0000a46b0, 0x0, 0x1, 0xc0000b6e80, 0x2, 0x2, ...)
	/home/mikefarah/dev/yq/pkg/yqlib/data_navigator.go:87 +0xb1b
github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).doTraverse(0xc00008fee0, 0xc000100dc0, 0x1239780, 0xc00011a1f0, 0xc0000a46a0, 0x1, 0x2, 0xc0000b6e80, 0x2, 0x2, ...)
	/home/mikefarah/dev/yq/pkg/yqlib/data_navigator.go:57 +0x5ee
github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).recurseMap.func1(0xc00008f660, 0x2, 0x2, 0x0, 0xc000118ff0, 0x3)
	/home/mikefarah/dev/yq/pkg/yqlib/data_navigator.go:131 +0x773
github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).visitDirectMatchingEntries(0xc00008fee0, 0xc000100c80, 0xc0000a7418, 0x6, 0xc0000a46a0, 0x1, 0x2, 0xc00008ffd0, 0x1, 0x1, ...)
	/home/mikefarah/dev/yq/pkg/yqlib/data_navigator.go:178 +0x202
github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).visitMatchingEntries(0xc00008fee0, 0xc000100c80, 0xc0000a7418, 0x6, 0xc0000a46a0, 0x1, 0x2, 0xc00008ffd0, 0x1, 0x1, ...)
	/home/mikefarah/dev/yq/pkg/yqlib/data_navigator.go:194 +0x1bc
github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).recurseMap(0xc00008fee0, 0xc000100c80, 0xc0000a7418, 0x6, 0xc0000a46a0, 0x1, 0x2, 0xc00008ffd0, 0x1, 0x1, ...)
	/home/mikefarah/dev/yq/pkg/yqlib/data_navigator.go:121 +0x158
github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).recurse(0xc00008fee0, 0xc000100c80, 0x1239780, 0xc00008fec0, 0xc0000a46a0, 0x1, 0x2, 0xc00008ffd0, 0x1, 0x1, ...)
	/home/mikefarah/dev/yq/pkg/yqlib/data_navigator.go:87 +0xb1b
github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).doTraverse(0xc00008fee0, 0xc000100c80, 0x1239780, 0xc00011a070, 0xc0000a4690, 0x2, 0x3, 0xc00008ffd0, 0x1, 0x1, ...)
	/home/mikefarah/dev/yq/pkg/yqlib/data_navigator.go:57 +0x5ee
github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).recurseMap.func1(0xc00008f670, 0x2, 0x2, 0x0, 0xc000118f30, 0x3)
	/home/mikefarah/dev/yq/pkg/yqlib/data_navigator.go:131 +0x773
github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).visitDirectMatchingEntries(0xc00008fee0, 0xc000100b40, 0xc0000a73d0, 0x6, 0xc0000a4690, 0x2, 0x3, 0xc000117700, 0x0, 0x0, ...)
	/home/mikefarah/dev/yq/pkg/yqlib/data_navigator.go:178 +0x202
github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).visitMatchingEntries(0xc00008fee0, 0xc000100b40, 0xc0000a73d0, 0x6, 0xc0000a4690, 0x2, 0x3, 0xc000117700, 0x0, 0x0, ...)
	/home/mikefarah/dev/yq/pkg/yqlib/data_navigator.go:194 +0x1bc
github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).recurseMap(0xc00008fee0, 0xc000100b40, 0xc0000a73d0, 0x6, 0xc0000a4690, 0x2, 0x3, 0xc000117700, 0x0, 0x0, ...)
	/home/mikefarah/dev/yq/pkg/yqlib/data_navigator.go:121 +0x158
github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).recurse(0xc00008fee0, 0xc000100b40, 0x1239780, 0xc00008fea0, 0xc0000a4690, 0x2, 0x3, 0xc000117700, 0x0, 0x0, ...)
	/home/mikefarah/dev/yq/pkg/yqlib/data_navigator.go:87 +0xb1b
github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).doTraverse(0xc00008fee0, 0xc000100b40, 0x1239780, 0x12cd7f0, 0xc0000a4680, 0x3, 0x4, 0xc000117700, 0x0, 0x0, ...)
	/home/mikefarah/dev/yq/pkg/yqlib/data_navigator.go:57 +0x5ee
github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).recurse(0xc00008fee0, 0xc000100a00, 0x1239780, 0x12cd7f0, 0xc0000a4680, 0x3, 0x4, 0xc000117700, 0x0, 0x0, ...)
	/home/mikefarah/dev/yq/pkg/yqlib/data_navigator.go:113 +0x33c
github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).doTraverse(0xc00008fee0, 0xc000100a00, 0x1239780, 0x12cd7f0, 0xc0000a4680, 0x3, 0x4, 0xc000117700, 0x0, 0x0, ...)
	/home/mikefarah/dev/yq/pkg/yqlib/data_navigator.go:53 +0x753
github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).Traverse(0xc00008fee0, 0xc000100a00, 0xc0000a4680, 0x3, 0x4, 0x100000001, 0x1)
	/home/mikefarah/dev/yq/pkg/yqlib/data_navigator.go:27 +0x16e
github.com/mikefarah/yq/v3/pkg/yqlib.(*lib).Update(0xc00008e8e0, 0xc000100a00, 0x12839ab, 0x5, 0xc0000b05c0, 0x14, 0xc0001008c0, 0x100000001, 0x1273401, 0x0, ...)
	/home/mikefarah/dev/yq/pkg/yqlib/lib.go:198 +0x32a
github.com/mikefarah/yq/v3/cmd.updateDoc.func1(0xc000100a00, 0x0, 0xc000100a00, 0x0)
	/home/mikefarah/dev/yq/cmd/utils.go:415 +0x28c
github.com/mikefarah/yq/v3/cmd.mapYamlDecoder.func1(0xc00008f610, 0xc00008f610, 0x600)
	/home/mikefarah/dev/yq/cmd/utils.go:367 +0x297
github.com/mikefarah/yq/v3/cmd.readStream(0x7ffeefbffa62, 0x27, 0xc0000b69c0, 0x0, 0x0)
	/home/mikefarah/dev/yq/cmd/utils.go:606 +0x24c
github.com/mikefarah/yq/v3/cmd.readAndUpdate(0x12d30c0, 0xc0000a0008, 0x7ffeefbffa62, 0x27, 0xc0001187b0, 0x0, 0x0)
	/home/mikefarah/dev/yq/cmd/utils.go:478 +0x26d
github.com/mikefarah/yq/v3/cmd.updateDoc(0x7ffeefbffa62, 0x27, 0xc0000fc240, 0x4, 0x4, 0x12d30c0, 0xc0000a0008, 0x4, 0x0)
	/home/mikefarah/dev/yq/cmd/utils.go:423 +0xe5
github.com/mikefarah/yq/v3/cmd.mergeProperties(0xc0000dd8c0, 0xc0000934d0, 0x2, 0x3, 0x0, 0x0)
	/home/mikefarah/dev/yq/cmd/merge.go:123 +0x699
github.com/spf13/cobra.(*Command).execute(0xc0000dd8c0, 0xc0000934a0, 0x3, 0x3, 0xc0000dd8c0, 0xc0000934a0)
	/home/mikefarah/dev/yq/vendor/github.com/spf13/cobra/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000dc2c0, 0x0, 0x12366c0, 0xc00008c058)
	/home/mikefarah/dev/yq/vendor/github.com/spf13/cobra/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/mikefarah/dev/yq/vendor/github.com/spf13/cobra/command.go:887
main.main()
	/home/mikefarah/dev/yq/yq.go:11 +0x2a
```

**Expected behavior**
```
Error, files cannot be merged. Schema deviates at line 2.
```

**Additional context**
If I run the merge in the opposite direction `yq m -x data1.yml data2.yml` it succeeds without error.

**Comment by mikefarah** [comment]
This is fixed in v4 (and won't be fixed in v3)

```
yq ea 'select(fileIndex == 0) * select(fileIndex==1)' examples/data1.yaml examples/data2.yaml
```

results in:

```
global:
  labels:
    - label1
```
