### ISSUE TITLE
Crash when RHS of the default operator // does not exist

### ISSUE THREAD

**Issue by vladlosev** [mikefarah/yq#838]
**Describe the bug**
When the RHS of the // operator does not exist (but LHS does), the operator invocation results in a crash.

Version of yq: 4.9.3
Operating system: mac
Installed via: asdf (https://github.com/asdf-vm/asdf)

```
$ echo '{"a":{"b":1}}' | yq eval '.a.c // .a.b' -
1
$ echo '{"a":{"b":1}}' | yq eval '.a.b // .a.c' -
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11cb306]

goroutine 1 [running]:
github.com/mikefarah/yq/v4/pkg/yqlib.alternativeFunc(0x14bf480, 0xc0001ab8f0, 0x0, 0xc000286001, 0xc0001439a0, 0x0, 0x0, 0x0, 0xc00010edb0)
	/home/runner/work/yq/yq/pkg/yqlib/operator_alternative.go:13 +0x66
github.com/mikefarah/yq/v4/pkg/yqlib.resultsForRhs(0x14bf480, 0xc0001ab8f0, 0x0, 0x1, 0xc0001439a0, 0xc000286060, 0x0, 0xc000260001, 0x12ea200, 0xc0001ab9e0, ...)
	/home/runner/work/yq/yq/pkg/yqlib/operators.go:30 +0x337
github.com/mikefarah/yq/v4/pkg/yqlib.doCrossFunc(0x14bf480, 0xc0001ab8f0, 0x0, 0x1, 0xc000230768, 0x12ea200, 0xc000230701, 0x12b0360, 0xc000230780, 0xc000260000, ...)
	/home/runner/work/yq/yq/pkg/yqlib/operators.go:74 +0x33b
github.com/mikefarah/yq/v4/pkg/yqlib.crossFunction(0x14bf480, 0xc0001ab7d0, 0x0, 0x1, 0xc000230768, 0x12ea200, 0x1, 0x128fe00, 0xc00010f0e0, 0x0, ...)
	/home/runner/work/yq/yq/pkg/yqlib/operators.go:98 +0x1c5
github.com/mikefarah/yq/v4/pkg/yqlib.alternativeOperator(0x14bf480, 0xc0001ab740, 0x0, 0x0, 0xc000230768, 0x0, 0x0, 0x1492500, 0x0, 0xc000269b18)
	/home/runner/work/yq/yq/pkg/yqlib/operator_alternative.go:5 +0xe8
github.com/mikefarah/yq/v4/pkg/yqlib.(*dataTreeNavigator).GetMatchingNodes(0x14bf480, 0xc0001ab740, 0x0, 0x0, 0xc000230768, 0x1000, 0xc00027c000, 0xc00010edb0, 0xc0001ab620, 0xc00025e340)
	/home/runner/work/yq/yq/pkg/yqlib/data_tree_navigator.go:37 +0x26e
github.com/mikefarah/yq/v4/pkg/yqlib.(*streamEvaluator).Evaluate(0xc000269d68, 0x7ffeefbff9f8, 0x1, 0x132cd18, 0xc0002581e0, 0xc000230768, 0x132e690, 0xc000122660, 0x12a0280, 0xc000142201)
	/home/runner/work/yq/yq/pkg/yqlib/stream_evaluator.go:100 +0x382
github.com/mikefarah/yq/v4/pkg/yqlib.(*streamEvaluator).EvaluateFiles(0xc000269d68, 0x7ffeefbff9eb, 0xc, 0xc000140330, 0x1, 0x1, 0x132e690, 0xc000122660, 0xc00015fd90, 0xc00015fd20)
	/home/runner/work/yq/yq/pkg/yqlib/stream_evaluator.go:63 +0x16c
github.com/mikefarah/yq/v4/cmd.evaluateSequence(0xc000146c80, 0xc000140320, 0x2, 0x2, 0x0, 0x0)
	/home/runner/work/yq/yq/cmd/evalute_sequence_command.go:115 +0x8b8
github.com/spf13/cobra.(*Command).execute(0xc000146c80, 0xc000140300, 0x2, 0x2, 0xc000146c80, 0xc000140300)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000146a00, 0x0, 0x127b3a0, 0xc000100058)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	/home/runner/work/yq/yq/yq.go:11 +0x2a
```

**Comment by mikefarah** [comment]
Yep that's a bug - will fix in the next release.

**Comment by vladlosev** [comment]
I am still observing the issue:
```
$ yq --version
yq version 4.9.4
$ echo '{"a":"2"}' | yq eval '.a // .b' -
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11cb306]

goroutine 1 [running]:
github.com/mikefarah/yq/v4/pkg/yqlib.alternativeFunc(0x14bf480, 0xc0001ab830, 0x0, 0xc0001abb01, 0xc0001017c0, 0x0, 0x0, 0x0, 0xc000110db0)
	/home/runner/work/yq/yq/pkg/yqlib/operator_alternative.go:13 +0x66
github.com/mikefarah/yq/v4/pkg/yqlib.resultsForRhs(0x14bf480, 0xc0001ab830, 0x0, 0x1, 0xc0001017c0, 0xc0001abb30, 0x0, 0xc000260001, 0x12ea200, 0xc0001ab920, ...)
	/home/runner/work/yq/yq/pkg/yqlib/operators.go:30 +0x338
github.com/mikefarah/yq/v4/pkg/yqlib.doCrossFunc(0x14bf480, 0xc0001ab830, 0x0, 0x1, 0xc000230738, 0x12ea200, 0xc000230701, 0x12b0360, 0xc000230750, 0xc000260000, ...)
	/home/runner/work/yq/yq/pkg/yqlib/operators.go:78 +0x33b
github.com/mikefarah/yq/v4/pkg/yqlib.crossFunction(0x14bf480, 0xc0001ab710, 0x0, 0x1, 0xc000230738, 0x12ea200, 0x1, 0x128fe00, 0xc0001110e0, 0x0, ...)
	/home/runner/work/yq/yq/pkg/yqlib/operators.go:102 +0x1c5
github.com/mikefarah/yq/v4/pkg/yqlib.alternativeOperator(0x14bf480, 0xc0001ab680, 0x0, 0x0, 0xc000230738, 0x0, 0x0, 0x1492500, 0x0, 0xc00026bb18)
	/home/runner/work/yq/yq/pkg/yqlib/operator_alternative.go:5 +0xe8
github.com/mikefarah/yq/v4/pkg/yqlib.(*dataTreeNavigator).GetMatchingNodes(0x14bf480, 0xc0001ab680, 0x0, 0x0, 0xc000230738, 0x1000, 0xc00027e000, 0xc000110db0, 0xc0001ab560, 0xc000260280)
	/home/runner/work/yq/yq/pkg/yqlib/data_tree_navigator.go:37 +0x26e
github.com/mikefarah/yq/v4/pkg/yqlib.(*streamEvaluator).Evaluate(0xc00026bd68, 0x7ffeefbff9cc, 0x1, 0x132cd18, 0xc0002581e0, 0xc000230738, 0x132e690, 0xc000124660, 0x12a0280, 0xc000100201)
	/home/runner/work/yq/yq/pkg/yqlib/stream_evaluator.go:100 +0x382
github.com/mikefarah/yq/v4/pkg/yqlib.(*streamEvaluator).EvaluateFiles(0xc00026bd68, 0x7ffeefbff9c3, 0x8, 0xc000142330, 0x1, 0x1, 0x132e690, 0xc000124660, 0xc00015fd90, 0xc00015fd20)
	/home/runner/work/yq/yq/pkg/yqlib/stream_evaluator.go:63 +0x16c
github.com/mikefarah/yq/v4/cmd.evaluateSequence(0xc000146c80, 0xc000142320, 0x2, 0x2, 0x0, 0x0)
	/home/runner/work/yq/yq/cmd/evalute_sequence_command.go:115 +0x8b8
github.com/spf13/cobra.(*Command).execute(0xc000146c80, 0xc000142300, 0x2, 0x2, 0xc000146c80, 0xc000142300)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000146a00, 0x0, 0x127b3a0, 0xc000102058)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	/home/runner/work/yq/yq/yq.go:11 +0x2a
```

**Comment by mikefarah** [comment]
🤦🏼  I think I fixed a different issue with `//` sorry!

**Comment by mikefarah** [comment]
ok try 4.9.5 - thanks for your patience!
